const tarotImages = {
  "The Fool": "https://crystal-tarot.github.io/crystal-tarot/images/00-TheFool.jpg",
  "The Magician": "https://crystal-tarot.github.io/crystal-tarot/images/01-TheMagician.jpg",
  "The High Priestess": "https://crystal-tarot.github.io/crystal-tarot/images/02-TheHighPriestess.jpg",
  "The Empress": "https://crystal-tarot.github.io/crystal-tarot/images/03-TheEmpress.jpg",
  "The Emperor": "https://crystal-tarot.github.io/crystal-tarot/images/04-TheEmperor.jpg",
  "The Hierophant": "https://crystal-tarot.github.io/crystal-tarot/images/05-TheHierophant.jpg",
  "The Lovers": "https://crystal-tarot.github.io/crystal-tarot/images/06-TheLovers.jpg",
  "The Chariot": "https://crystal-tarot.github.io/crystal-tarot/images/07-TheChariot.jpg",
  "Strength": "https://crystal-tarot.github.io/crystal-tarot/images/08-Strength.jpg",
  "The Hermit": "https://crystal-tarot.github.io/crystal-tarot/images/09-TheHermit.jpg",
  "Wheel of Fortune": "https://crystal-tarot.github.io/crystal-tarot/images/10-WheelOfFortune.jpg",
  "Justice": "https://crystal-tarot.github.io/crystal-tarot/images/11-Justice.jpg",
  "The Hanged Man": "https://crystal-tarot.github.io/crystal-tarot/images/12-TheHangedMan.jpg",
  "Death": "https://crystal-tarot.github.io/crystal-tarot/images/13-Death.jpg",
  "Temperance": "https://crystal-tarot.github.io/crystal-tarot/images/14-Temperance.jpg",
  "The Devil": "https://crystal-tarot.github.io/crystal-tarot/images/15-TheDevil.jpg",
  "The Tower": "https://crystal-tarot.github.io/crystal-tarot/images/16-TheTower.jpg",
  "The Star": "https://crystal-tarot.github.io/crystal-tarot/images/17-TheStar.jpg",
  "The Moon": "https://crystal-tarot.github.io/crystal-tarot/images/18-TheMoon.jpg",
  "The Sun": "https://crystal-tarot.github.io/crystal-tarot/images/19-TheSun.jpg",
  "Judgement": "https://crystal-tarot.github.io/crystal-tarot/images/20-Judgement.jpg",
  "The World": "https://crystal-tarot.github.io/crystal-tarot/images/21-TheWorld.jpg",
  "Ace of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups01.jpg",
  "Two of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups02.jpg",
  "Three of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups03.jpg",
  "Four of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups04.jpg",
  "Five of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups05.jpg",
  "Six of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups06.jpg",
  "Seven of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups07.jpg",
  "Eight of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups08.jpg",
  "Nine of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups09.jpg",
  "Ten of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups10.jpg",
  "Page of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups11.jpg",
  "Knight of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups12.jpg",
  "Queen of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups13.jpg",
  "King of Cups": "https://crystal-tarot.github.io/crystal-tarot/images/Cups14.jpg",
  "Ace of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles01.jpg",
  "Two of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles02.jpg",
  "Three of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles03.jpg",
  "Four of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles04.jpg",
  "Five of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles05.jpg",
  "Six of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles06.jpg",
  "Seven of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles07.jpg",
  "Eight of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles08.jpg",
  "Nine of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles09.jpg",
  "Ten of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles10.jpg",
  "Page of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles11.jpg",
  "Knight of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles12.jpg",
  "Queen of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles13.jpg",
  "King of Pentacles": "https://crystal-tarot.github.io/crystal-tarot/images/Pentacles14.jpg",
  "Ace of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords01.jpg",
  "Two of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords02.jpg",
  "Three of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords03.jpg",
  "Four of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords04.jpg",
  "Five of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords05.jpg",
  "Six of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords06.jpg",
  "Seven of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords07.jpg",
  "Eight of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords08.jpg",
  "Nine of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords09.jpg",
  "Ten of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords10.jpg",
  "Page of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords11.jpg",
  "Knight of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords12.jpg",
  "Queen of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords13.jpg",
  "King of Swords": "https://crystal-tarot.github.io/crystal-tarot/images/Swords14.jpg",
  "Ace of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands01.jpg",
  "Two of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands02.jpg",
  "Three of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands03.jpg",
  "Four of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands04.jpg",
  "Five of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands05.jpg",
  "Six of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands06.jpg",
  "Seven of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands07.jpg",
  "Eight of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands08.jpg",
  "Nine of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands09.jpg",
  "Ten of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands10.jpg",
  "Page of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands11.jpg",
  "Knight of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands12.jpg",
  "Queen of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands13.jpg",
  "King of Wands": "https://crystal-tarot.github.io/crystal-tarot/images/Wands14.jpg"
};